# Generated by Django 5.1 on 2025-02-13 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('idobra_social', models.AutoField(db_column='idObra_social', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('tipo', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'obra_social',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(db_column='idPaciente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField(unique=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('obra_social', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=256)),
                ('diabetes', models.BooleanField()),
                ('hipertension', models.BooleanField()),
                ('fumador', models.BooleanField()),
                ('alergias', models.CharField(blank=True, max_length=256, null=True)),
                ('antecedentes', models.CharField(blank=True, max_length=256, null=True)),
                ('cirugias', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.IntegerField()),
                ('descripcion', models.CharField(max_length=256)),
                ('gravedad', models.CharField(max_length=256)),
                ('tratamiento', models.CharField(max_length=256)),
                ('codigo_cie_10', models.CharField(db_column='codigo_CIE-10', max_length=10)),
                ('idpaciente', models.ForeignKey(db_column='idPaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PacienteObraSocial',
            fields=[
                ('idpaciente_obra_social', models.AutoField(db_column='idPaciente_Obra_Social', primary_key=True, serialize=False)),
                ('nro_afiliado', models.IntegerField()),
                ('obra_social_paciente', models.ForeignKey(db_column='Obra_Social_Paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.obrasocial')),
                ('paciente_obra_social', models.ForeignKey(db_column='Paciente_Obra_Social', on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'paciente_obra_social',
                'managed': True,
            },
        ),
    ]
