# Generated by Django 5.1 on 2024-09-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_alter_enfermero_options_alter_medico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.IntegerField()),
                ('descripcion', models.CharField(max_length=256)),
                ('gravedad', models.CharField(max_length=256)),
                ('tratamiento', models.CharField(max_length=256)),
                ('codigo_cie_10', models.CharField(db_column='codigo_CIE-10', max_length=10)),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('idobra_social', models.AutoField(db_column='idObra_social', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('tipo', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'obra_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.OneToOneField(db_column='idPaciente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personal.persona')),
                ('obra_social', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacienteObraSocial',
            fields=[
                ('idpaciente_obra_social', models.AutoField(db_column='idPaciente_Obra_Social', primary_key=True, serialize=False)),
                ('nro_afiliado', models.IntegerField()),
            ],
            options={
                'db_table': 'paciente_obra_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('idsignos_vitales', models.AutoField(db_column='idSignos_vitales', primary_key=True, serialize=False)),
                ('temperatura_corporal', models.CharField(max_length=45)),
                ('pulso', models.CharField(max_length=45)),
                ('frecuencia_respiratoria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'signos_vitales',
                'managed': False,
            },
        ),
    ]
