# Generated by Django 5.1 on 2024-09-10 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idhabitacion', models.AutoField(db_column='idHabitacion', primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('cantidad_camas', models.IntegerField()),
                ('es_privada', models.IntegerField()),
                ('es_vip', models.IntegerField()),
                ('tipo', models.CharField(max_length=256)),
                ('disponibilidad', models.IntegerField()),
            ],
            options={
                'db_table': 'habitacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('idsector', models.AutoField(db_column='idSector', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=256)),
                ('cantidad_habitaciones', models.IntegerField()),
                ('piso', models.IntegerField()),
            ],
            options={
                'db_table': 'sector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('idcama', models.AutoField(db_column='idCama', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupada')], default='L', max_length=1)),
                ('paciente', models.ForeignKey(blank=True, db_column='idPaciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.paciente')),
                ('habitacion', models.ForeignKey(db_column='idHabitacion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='camas', to='habitaciones.habitacion')),
            ],
            options={
                'db_table': 'cama',
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='idsector',
            field=models.ForeignKey(db_column='idSector', on_delete=django.db.models.deletion.DO_NOTHING, to='habitaciones.sector'),
        ),
    ]
