# Generated by Django 5.1 on 2024-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('idcama', models.AutoField(db_column='idCama', primary_key=True, serialize=False)),
                ('nro_cama', models.TextField()),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cama',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idhabitacion', models.AutoField(db_column='idHabitacion', primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('cantidad_camas', models.IntegerField()),
                ('es_privada', models.IntegerField()),
                ('es_vip', models.IntegerField()),
                ('tipo', models.CharField(max_length=256)),
                ('disponibilidad', models.IntegerField()),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('idsector', models.AutoField(db_column='idSector', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=256)),
                ('cantidad_habitaciones', models.IntegerField()),
                ('piso', models.IntegerField()),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
    ]
