# Generated by Django 5.1 on 2025-02-13 01:38

import habitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_expiracion',
            field=models.DateTimeField(default=habitaciones.models.default_expiracion),
        ),
    ]
