# Generated by Django 5.1 on 2024-09-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cama',
            options={},
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={},
        ),
    ]
