# Generated by Django 5.1 on 2024-12-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('idatencion', models.AutoField(db_column='idAtencion', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('detalles', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'atencion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('idinternacion', models.AutoField(db_column='idInternacion', primary_key=True, serialize=False)),
                ('fecha_admicion', models.DateTimeField()),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('nota_ingreso', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'internacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('idmedicacion', models.AutoField(db_column='idMedicacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('hora_medicacion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'medicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('idseguimento', models.AutoField(db_column='idSeguimiento', primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'seguimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('idsignos_vitales', models.AutoField(db_column='idSignos_vitales', primary_key=True, serialize=False)),
                ('temperatura_corporal', models.CharField(max_length=45)),
                ('pulso', models.CharField(max_length=45)),
                ('frecuencia_respiratoria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'signos_vitales',
                'managed': True,
            },
        ),
    ]
