# Generated by Django 5.1 on 2025-02-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0001_initial'),
        ('pacientes', '0002_delete_diagnostico'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, default=None, null=True)),
                ('detalles', models.CharField(blank=True, max_length=256, null=True)),
                ('gravedad', models.CharField(blank=True, max_length=256, null=True)),
                ('tratamiento', models.CharField(blank=True, max_length=256, null=True)),
                ('idmedico', models.ForeignKey(db_column='idMedico', on_delete=django.db.models.deletion.DO_NOTHING, to='personal.medico')),
                ('idmedico_derivado', models.ForeignKey(blank=True, db_column='idMedico_derivado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagnostico_como_derivado', to='personal.medico')),
                ('idpaciente', models.ForeignKey(db_column='idPaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Atencion',
        ),
    ]
