# Generated by Django 5.1 on 2025-02-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0002_diagnostico_delete_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='idinternacion',
            field=models.ForeignKey(blank=True, db_column='idInternacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='internacion.internacion'),
        ),
    ]
