# Generated by Django 5.1 on 2025-01-16 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicacion',
            name='seguimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='internacion.seguimiento'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='seguimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales_set', to='internacion.seguimiento'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='medicacion',
            field=models.ForeignKey(blank=True, db_column='medicacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seguimientos', to='internacion.medicacion'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='signos_vitales',
            field=models.ForeignKey(blank=True, db_column='signos_vitales', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seguimientos_set', to='internacion.signosvitales'),
        ),
    ]
