# Generated by Django 5.1 on 2025-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0003_medicacion_seguimiento_signosvitales_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicacion',
            name='hora_medicacion',
            field=models.TimeField(max_length=45),
        ),
    ]
