# Generated by Django 5.1 on 2025-01-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internacion', '0004_alter_medicacion_hora_medicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='medicacion',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='signos_vitales',
        ),
    ]
