# Generated by Django 5.1 on 2024-09-10 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('persona_idpersona', models.OneToOneField(db_column='Persona_idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personal.persona')),
                ('matricula', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'enfermero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('persona_idpersona', models.OneToOneField(db_column='Persona_idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personal.persona')),
                ('especializacion', models.CharField(max_length=45)),
                ('matricula', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('persona_idpersona', models.OneToOneField(db_column='Persona_idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personal.persona')),
            ],
            options={
                'db_table': 'recepcionista',
                'managed': True,
            },
        ),
    ]
