# Generated by Django 5.1 on 2024-09-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfermero',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='recepcionista',
            options={'managed': False},
        ),
    ]
