# Generated by Django 5.1 on 2025-01-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_remove_persona_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='persona',
            managers=[
            ],
        ),
    ]
